import { ReactNode } from "react";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import Providers from "./providers";
import {
  Button,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
} from "./client-cmps";
import Link from "next/link";

const robotoFlex = Roboto_Flex({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Next.js TODOS",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Providers>
        <body className={robotoFlex.className}>
          <Navbar className="shadow-md">
            <NavbarBrand>
              <p className="font-bold text-inherit">TODOS</p>
            </NavbarBrand>
            <NavbarContent justify="end">
              <NavbarItem>
                <Button as={Link} color="primary" href="/new">
                  Add
                </Button>
              </NavbarItem>
            </NavbarContent>
          </Navbar>
          {children}
        </body>
      </Providers>
    </html>
  );
}
